# Generated by Django 5.0.3 on 2024-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_server', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(default='images/carousel/default-image.jpg', upload_to='images/carousel/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/categories/default-image.jpg', upload_to='images/categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default-image.jpg', upload_to='images/products/'),
        ),
    ]
