# Generated by Django 5.0.3 on 2024-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_server', '0003_delete_productimage_remove_carouselitem_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(default='images/carousel/default-carousel.jpg', upload_to='images/carousel/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/categories/default-category.jpg', upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default-product.jpg', upload_to='images/products/'),
        ),
    ]
