# Generated by Django 5.0.3 on 2024-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_server', '0005_alter_carouselitem_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.TextField(max_length=255),
        ),
    ]
